accounts/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.contrib.auth import views as auth_views
from django.urls import path, include
from accounts.views import home, createStudent, createTeacher, userdetails
app_name = 'accounts' # for namespacing

# urls  
urlpatterns = [
    path('', home, name='home'),
    path('signup/', include(([
        path('student', createStudent, name='createStudent'),
        path('teacher', createTeacher, name='createTeacher'),
])),),
    path('deets/<pk>', userdetails.as_view(), name='details'), # user detail from class view
    # using django default login and logout views
    path('login', auth_views.LoginView.as_view(template_name='accounts/login.html'), name='login'),
    path('logout', auth_views.LogoutView.as_view(template_name='home.html'), name='logout'),
]



if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

multi_accounts/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls), # admin site should be at the top of the url
    path('', include('accounts.urls')),
]

templates/layouts/base.html
<!doctype html>
<html lang="en">
  <head>
    <!-- Required meta tags -->
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">

    <!-- Bootstrap CSS -->
    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap@4.5.3/dist/css/bootstrap.min.css" integrity="sha384-TX8t27EcRE3e/ihU7zmQxVncDAy5uIKz4rEkgIXeMed4M0jlfIDPvg6uqKI2xXr2" crossorigin="anonymous">
  </head>
    
    <nav class="navbar navbar-expand-lg navbar-light bg-light">
        <a class="navbar-brand" href="{% url 'accounts:home' %}">Accounts</a>
        <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarNavAltMarkup" aria-controls="navbarNavAltMarkup" aria-expanded="false" aria-label="Toggle navigation">
          <span class="navbar-toggler-icon"></span>
        </button>
        <div class="collapse navbar-collapse" id="navbarNavAltMarkup">
          <div style="width: 80%; height: auto;"></div>
          <ul class="nav navbar-nav navbar-right">
            {% if not request.user.is_authenticated %}
            <li class="dropdown fade-in">
              <a href="javascript:void(0);" class="btn btn-pill btn-air btn-sm"
                 role="button" id="userMenu" data-toggle="dropdown"
                 aria-haspopup="true" aria-expanded="false">
                  <span>Sign Up</span>
              </a>
              <div class="dropdown-menu dropdown-menu-right" aria-labelledby="userMenu">
                  
                  <a class="dropdown-item" href="{% url 'accounts:createStudent' %}"role="button">
                      <i class="ion-md-contact"></i>
                      <span>Student</span>
                  </a>
                  
                 <a class="dropdown-item" href="{% url 'accounts:createTeacher' %}" class="btn-pill btn-air btn-sm btn-danger" role="button">
                      <i class="ion-md-contact"></i>
                      <span>Teacher</span>
                  </a>
                  
              </div>
                  
              </li>
              
              <li><a class="btn btn-pill btn-air btn-sm" role="button" aria-haspopup="true" aria-expanded="false" href="{% url 'accounts:login' %}">Login <span class="sr-only">(current)</span></a></li>
            {% else %}
              <li><a class="nav-link active" href="{% url 'accounts:details' request.user.pk  %}">Welcome, <b>{{ request.user.first_name }}</b><span class="sr-only">(current)</span></a></li>
              <li><a class="nav-link active" href="{% url 'accounts:logout' %}">Logout <span class="sr-only">(current)</span></a></li>
            {% endif %}
          </ul>
        </div>
    </nav>

    <div style="margin-left: 4%; margin-right: 4%; margin-top: 1%;">
      <h1 class="text-center">{% block header %} {% endblock %}</h1>

      {% block content %}

      {% endblock %}
    </div>

    <!-- jQuery and Bootstrap Bundle (includes Popper) -->
    <script src="https://code.jquery.com/jquery-3.5.1.slim.min.js" integrity="sha384-DfXdz2htPH0lsSSs5nCTpuj/zy4C+OGpamoFVy38MVBnE+IbbVYUew+OrCXaRkfj" crossorigin="anonymous"></script>
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@4.5.3/dist/js/bootstrap.bundle.min.js" integrity="sha384-ho+j7jyWK8fNQe+A12Hb8AhRq26LrZ/JpcUGGOn+Y7RsweNrtN/tE3MoK7ZeZDyx" crossorigin="anonymous"></script>

  </body>
</html>